services:
  node1:
    container_name: node1
    image: tokenfactory-node
    networks:
      tokenfactory-net:
        ipv4_address: 172.22.0.2
    environment:
      - NODE_NAME=node1
      - ROLE=validator
    volumes:
      - node1_data:/root/.tokenfactory
    ports:
      - "26656:26656"
      - "26657:26657"
      - "1317:1317"
    command: ["sleep", "infinity"] 

  node2:
    container_name: node2
    image: tokenfactory-node
    networks:
      tokenfactory-net:
        ipv4_address: 172.22.0.3
    environment:
      - NODE_NAME=node2
      - ROLE=validator
    volumes:
      - node2_data:/root/.tokenfactory
    ports:
      - "26658:26656"
      - "26659:26657"
      - "1318:1317"
    command: ["sleep", "infinity"] 
    
  node3:
    container_name: node3
    image: tokenfactory-node
    networks:
      tokenfactory-net:
        ipv4_address: 172.22.0.4
    environment:
      - NODE_NAME=node3
      - ROLE=regular
    volumes:
      - node3_data:/root/.tokenfactory
    ports:
      - "26660:26656"
      - "26661:26657"
      - "1319:1317"
    command: ["sleep", "infinity"] 

networks:
  tokenfactory-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.22.0.0/16
          gateway: 172.22.0.1

volumes:
  node1_data:
  node2_data:
  node3_data:
